### ISSUE TITLE
No dist folder in package -> webpack can't import module

### ISSUE THREAD

**Issue by TomDeSmet** [mohamadkhani/vue-simple-range-slider#3]
Your package doesn't have a dist folder so Webpack can't find the module when importing.
Is this how it should be? If so, what triggers the build? It doesn't get triggered by npm install.

**Comment by Dizuite** [comment]
Hello, someone find how to use it with npm finally ? I try to use it with nuxt but it doesn't works

**Comment by ghost** [comment]
Hey guys. 
I had forgotten to add the dist folder to git and npm repo.
I added it to git and npm repo. Now it simply works.
Thank you for reporting the issue.
